In [39]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/digit-recognizer/sample_submission.csv
/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv


In [40]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [41]:
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [42]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255
_,m_train = X_train.shape

In [46]:
def init_params():
    w1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    w2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5

    return w1, b1, w2, b2

def ReLU(z):
    return np.maximum(0, z)

def softmax(z):
    A = np.exp(z) / sum(np.exp(z))
    return A
    
def forward_prop(w1, b1, w2, b2, X):
    z1 = w1.dot(X) + b1
    A1 = ReLU(z1)
    z2 = w2.dot(A1) + b2
    A2 = softmax(z2)
    return z1, A1, z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_relu(z):
    return z > 0
    
def back_prop(z1, A1, z2, A2, w2, X, Y):
    
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1/m * np.sum(dZ2, axis=1, keepdims=True)

    dZ1 = w2.T.dot(dZ2) * deriv_relu(z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1/m * np.sum(dZ1, axis=1, keepdims=True)
    return dW1, db1, dW2, db2

def update_params(w1, b1, w2, b2, dW1, db1, dW2, db2, alpha):
    w1 = w1 - alpha * dW1
    b1 = b1 - alpha * db1
    w2 = w2 - alpha * dW2
    b2 = b2 - alpha * db2
    return w1, b1, w2, b2

In [47]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
    w1, b1, w2, b2 = init_params()
    for i in range(iterations):
        z1, A1, z2, A2 = forward_prop(w1, b1, w2, b2, X)
        dW1, db1, dW2, db2 = back_prop(z1, A1, z2, A2, w2, X, Y)
        w1, b1, w2, b2, = update_params(w1, b1, w2, b2, dW1, db1, dW2, db2, alpha)
        if i % 50 == 0:
            print("Iteration: ", i)
            print("Accuracy: ", get_accuracy(get_predictions(A2), Y))
    return w1, b1, w2, b2

In [48]:
w1, b1, w2, b2 = gradient_descent(X_train, Y_train, 500, 0.1)

Iteration:  0
[5 7 7 ... 7 7 7] [0 7 7 ... 2 5 8]
Accuracy:  0.14895121951219512
Iteration:  50
[0 7 9 ... 2 9 8] [0 7 7 ... 2 5 8]
Accuracy:  0.5581219512195122
Iteration:  100
[0 7 9 ... 2 5 8] [0 7 7 ... 2 5 8]
Accuracy:  0.6787804878048781
Iteration:  150
[0 7 9 ... 2 5 8] [0 7 7 ... 2 5 8]
Accuracy:  0.7349024390243902
Iteration:  200
[0 7 9 ... 2 5 8] [0 7 7 ... 2 5 8]
Accuracy:  0.7694390243902439
Iteration:  250
[0 7 9 ... 2 5 8] [0 7 7 ... 2 5 8]
Accuracy:  0.7935121951219513
Iteration:  300
[0 7 9 ... 2 5 8] [0 7 7 ... 2 5 8]
Accuracy:  0.8107073170731708
Iteration:  350
[0 7 9 ... 2 5 8] [0 7 7 ... 2 5 8]
Accuracy:  0.8234390243902439
Iteration:  400
[0 7 9 ... 2 5 8] [0 7 7 ... 2 5 8]
Accuracy:  0.8330731707317073
Iteration:  450
[0 7 9 ... 2 5 8] [0 7 7 ... 2 5 8]
Accuracy:  0.8409024390243902
